//
//  DeveloperSettingsView.swift
//  App (Generated by SwiftyLaunch 1.5.0)
//  https://docs.swiftylaun.ch/module/app#developer-view
//
//  Use this developer settings view to adjust settings,
//  enable/disable features, etc. on the fly to help you with the development process.
//
//  This View is only shown in 'Debug / Development' Release Mode
//  DEBUG = Not App Store or TestFlight build
//

import NotifKit
import SharedKit
import SupabaseKit
import SwiftUI
import CrashlyticsKit

struct DeveloperSettingsView: View {
	@EnvironmentObject var db: DB

	@State var showOnboarding = false
	@State var showFeatureSheet = false
	@State var showSignIn = false

	@State var showViewWithNoAccess = false
	@State var showViewWithAccessIfSignedIn = false

	var body: some View {
		NavigationStack {
			#if DEBUG
				List {
					Section {
						Button("Show Onboarding") {
							showOnboarding = true
						}

						Button("Show Feature Sheet") {
							showFeatureSheet = true
						}

						Button("Reset UserDefaults") {
							UserDefaults.standard.clear()
						}

						Button("Send InApp Notification") {
							showInAppNotification(
								.info,
								content: InAppNotificationContent(
									title: "Info Notification",
									message: "This is a normal Notification"),
								size: .normal
							) {
								print("hello")
							}
						}

						Button("Send Compact InApp Notification") {
							showInAppNotification(
								content: .init(
									title: "Custom Notification",
									message: "Compact Notification"),
								style: .init(
									sfSymbol: "star.fill", symbolColor: .indigo,
									size: .compact)
							)
						}
					}

					Section {
						Button("Send Test Event to Sentry") {
							Crashlytics.shared.captureError(
								NSError(domain: "test", code: 1234, userInfo: [NSLocalizedDescriptionKey: "This is a test event"])
							)
							showInAppNotification(
								.success,
								content: InAppNotificationContent(
									title: "Test Event Sent",
									message: "Check Sentry dashboard"
								),
								size: .compact
							)
						}

						Button("Trigger Fatal Error", role: .destructive) {
							fatalError("This is a test crash triggered from developer settings")
						}
					} header: {
						Text("Crash Testing")
					}

					Section {
						// just examples on how to use `askUserFor` actions.
						Button("Will Ask for Review on 10th tap") {
							askUserFor(.appRating) {
								print(
									"Won't show rating sheet. Already prompted or not performing for the 10th time."
								)
							} onDismiss: {
								print("User Dimissing Rating Sheet.")
							}
						}

						Button("Ask for Push Notifications Permission") {
							PushNotifications.showNotificationsPermissionsSheet()
						}
					} header: {
						Text("Ask User For...")
					}

					Section {
						Text("User ID")
							.badge("\(db.currentUser?.id.uuidString ?? "Not Logged In")")
							.textSelection(.enabled)  // allows the user to hold to copy

						Button("Show Sign In") {
							showSignIn = true
						}

						Button("Sign Out", role: .destructive) {
							Task {
								try? await db.signOut()
							}
						}

						Button("You probably can't see what this opens") {
							showViewWithNoAccess = true
						}

						Button("You can see what this opens (if you're signed in)") {
							showViewWithAccessIfSignedIn = true
						}
					} header: {
						Text("AuthKit & DBKit (Supabase)")
					}

				}
				.navigationTitle("Developer Settings")
//				.sheet(isPresented: $showFeatureSheet) {
//					ShowFeatureSheetOnNewAppVersionModifier.WhatsNewView {
//						showFeatureSheet = false
//					}
//				}
				.sheet(isPresented: $showOnboarding) {
					OnboardingView {
						showOnboarding = false
					}
				}
				.sheet(isPresented: $showSignIn) {
					SignInView(db: db) {
						showSignIn = false
					}
				}

				.sheet(isPresented: $showViewWithNoAccess) {
					Text("Super Secret View for a user with ID: '00000000-0000-0000-0000-000000000000'")
						.visibleOnlyToUserWithID(
							UUID(uuidString: "00000000-0000-0000-0000-000000000000"), db: db
						) {
							showViewWithNoAccess = false
						}
				}
				.sheet(isPresented: $showViewWithAccessIfSignedIn) {
					// if current id is nil, the id for this view will be set to zeroes, -> won't be visible no matter what your id is
					Text(
						"Super Secret View for a user with ID: \(String(describing: db.currentUser?.id ?? UUID(uuidString: "00000000-0000-0000-0000-000000000000")))"
					)
					.visibleOnlyToUserWithID(db.currentUser?.id, db: db) {
						showViewWithAccessIfSignedIn = false
					}
				}

			#endif
		}
	}
}

#Preview {
	DeveloperSettingsView()
		.environmentObject(DB())
}
