//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 1.5.0)
//  https://docs.swiftylaun.ch/module/app
//

import NotifKit
import SharedKit
import SupabaseKit
import SwiftUI

struct ContentView: View {
	var body: some View {
		TabView {
			HomeView()
				.tabItem {
					Image(systemName: "house")
				}
			
			ExploreView()
				.tabItem {
					Image(systemName: "magnifyingglass")
				}
			
			ProgressView()
				.tabItem {
					Image(systemName: "chart.bar")
				}
			
			ProfileView()
				.tabItem {
					Image(systemName: "person")
				}
			
			#if DEBUG
			// Use this to create quick settings and toggles to streamline the development process.
			DeveloperSettingsView()
				.tabItem { Label("Developer", systemImage: "hammer") }
			#endif
		}
		.tint(.brandPrimary) // Set the tab bar tint to our brand color
	}
}

#Preview {
	ContentView()
}
