//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 1.5.0)
//  https://docs.swiftylaun.ch/module/app
//

import NotifKit
import SharedKit
import SupabaseKit
import SwiftUI

struct ContentView: View {
	@EnvironmentObject private var db: DB
	@EnvironmentObject private var progressStore: LocalProgressStore
	@EnvironmentObject private var syncManager: SupabaseSyncManager
	
	var body: some View {
		TabView {
			HomeView()
				.tabItem {
					Label("Home", systemImage: "house.fill")
				}
			
			ExploreView()
				.tabItem {
					Label("Explore", systemImage: "square.grid.2x2.fill")
				}
			
			ProgressView(progressStore: progressStore, syncManager: syncManager)
				.tabItem {
					Label("Progress", systemImage: "chart.bar.fill")
				}
			
			#if DEBUG
			// Use this to create quick settings and toggles to streamline the development process.
			DeveloperSettingsView()
				.tabItem { 
					Label("Developer", systemImage: "hammer.fill")
				}
			#endif
		}
		.tint(.brandPrimary) // Set the tab bar tint to our brand color
		.preferredColorScheme(.dark)
		.safeAreaInset(edge: .bottom) {
			Color.clear.frame(height: 8) // Add extra padding at the top of the tab bar
		}
	}
}

